### PR TITLE
+ Extend body parsing capabilities to match with imap_fetchstructure

### PR DESCRIPTION
**Pull request by dicode-nl**
I've extended the BodyStructure.php to be able to parse more different message types and match output with imap_fetchstructure. Tested with over 2000+ messages

### CODE REVIEW

**Comment by darkworks** [comment]
this is much needed , please merge it

**Comment by ProteanHub** [comment]
This code works beautifully and fixed the issues we were having with duplicated html body, and attachments not being assigned properly. Thank you!

**Comment by Orgoth** [comment]
@dicode-nl https://github.com/ddeboer/imap/issues/443
Fix for S-MIME-Messages:
BodyStructure.php:45

```php
        $section = 'parts';
        $subType = 'ALTERNATIVE';
        if( is_scalar($structure[2]) && strtolower($structure[2]) == 'signed' ){
            $subType = 'SIGNED';
        }
```

BodyStructure.php:69

```php
            if (is_scalar($item) && strtolower($item) == '*') {
                $subType = '*';
                $section = 'parameters';
                continue;
            }

            if (is_scalar($item) && strtolower($item) == 'signed') {
                $section = 'parameters';
                continue;
            }
```

**Comment by dicode-nl** [comment]
@Orgoth can't this be fixed in a single statement like the rest of the base types
```
            if (is_scalar($item) && strtolower($item) == 'signed') {
                $subType = 'SIGNED';
                $section = 'parameters';
                continue;
            }
```

**Comment by Orgoth** [comment]
> @Orgoth can't this be fixed in a single statement like the rest of the base types
> 
> ```
>             if (is_scalar($item) && strtolower($item) == 'signed') {
>                 $subType = 'SIGNED';
>                 $section = 'parameters';
>                 continue;
>             }
> ```

Since I gradually adjusted to imap_fetch, I didn't notice this at all.
Of course, it can be shortened to this minimal version.
Thanks for the hint.

The next Message is also smime, but without signed structure.

```
* 1 FETCH (UID 8692 BODYSTRUCTURE ("application" "pkcs7-mime" ("smime-type" "signed-data" "name" "smime.p7m") NIL NIL "base64" 106418 NIL ("attachment" ("filename" "smime.p7m")) ("de-DE") NIL))
```

**Comment by Orgoth** [comment]
The return object must be updated, with this new message-type, the parameter ifdparameters must be set to 1 and dparameters must be set too.

```php
stdClass#1
{
  [type] => 3
  [encoding] => 3
  [ifsubtype] => 1
  [subtype] => string(10): "PKCS7-MIME"
  [ifdescription] => 0
  [ifid] => 0
  [bytes] => 106418
  [ifdisposition] => 1
  [disposition] => string(10): "attachment"
  [ifdparameters] => 1
  [dparameters] => array(1)
  {
    [0] => stdClass#2
    {
      [attribute] => string(8): "filename"
      [value] => string(9): "smime.p7m"
    }
  }
  [ifparameters] => 1
  [parameters] => array(2)
  {
    [0] => stdClass#3
    {
      [attribute] => string(10): "smime-type"
      [value] => string(11): "signed-data"
    }
    [1] => stdClass#4
    {
      [attribute] => string(4): "name"
      [value] => string(9): "smime.p7m"
    }
  }
}
```

**Comment by Orgoth** [comment]
First possible solution:

BodyStructure.php:40 add
```php
        if (isset($structure[0]) && is_scalar($structure[0]) && strtolower($structure[0]) == 'application') {
            return self::extractPart($structure);
        }
```

return matches 1:1 with original imap_fetchstructure.

**Comment by dicode-nl** [comment]
@Orgoth could you send me the json for fromBodyStructure so I can run it trough the parser?

**Comment by Orgoth** [comment]
> First possible solution:
> 
> BodyStructure.php:40 add
> 
> ```
>         if (isset($structure[0]) && is_scalar($structure[0]) && strtolower($structure[0]) == 'application') {
>             return self::extractPart($structure);
>         }
> ```
> 
> return matches 1:1 with original imap_fetchstructure.

JSON
```json
["application","pkcs7-mime",["smime-type","signed-data","name","smime.p7m"],null,null,"base64","106418",null,["attachment",["filename","smime.p7m"]],["de-DE"],null]
```

> @Orgoth can't this be fixed in a single statement like the rest of the base types
> 
> ```
>             if (is_scalar($item) && strtolower($item) == 'signed') {
>                 $subType = 'SIGNED';
>                 $section = 'parameters';
>                 continue;
>             }
> ```

JSON
```json
[[[["text","plain",["charset","utf-8"],null,null,"QUOTED-PRINTABLE","6490","127",null,["inline",null],null,null],["text","html",["charset","utf-8"],null,null,"QUOTED-PRINTABLE","54183","1044",null,["inline",null],null,null],"alternative",["boundary","_000_b3d8e91e8fa2406191c2926c076849dcwwkde_"],null,null,null],["image","png",["name","image001.png"],"","image001.png","base64","272",null,["inline",["filename","image001.png","size","198","creation-date","Mon, 14 Jun 2021 11:43:16 GMT","modification-date","Mon, 14 Jun 2021 11:43:16 GMT"]],null,null],"related",["boundary","_004_b3d8e91e8fa2406191c2926c076849dcwwkde_","type","multipart\/alternative"],null,null,null],["application","pkcs7-signature",["name","smime.p7s"],null,null,"BASE64","9664",null,["attachment",["filename","smime.p7s"]],null,null],"signed",["boundary","NoSpamProxy_7ddeb92e-da00-4a8c-8234-193e7adea21b","protocol","application\/pkcs7-signature","micalg","sha256"],null,["de-DE"],null]
```

**Comment by dicode-nl** [comment]
Seems legit to me, pushed the changes to this PR.

**Comment by Orgoth** [comment]
A delivery report "mailer-daemon"

Adding the following line, helps to get in the right direction, but the first part gets a mixed subpart, which should not be there.
```php
            if (is_scalar($item) && strtolower($item) == 'report') {
                $subType = 'REPORT';
                $section = 'parameters';
                continue;
            }
```

```json
[["text","plain",["charset","utf-8"],null,"Notification","8bit","517","14",null,null,null,null],["message","delivery-status",null,null,"Delivery report","7bit","384",null,null,null,null],["message","rfc822",null,null,"Undelivered Message","8bit","3021",["Mon, 5 Sep 2022 13:57:09 +0200","Auskunft nach Art. 15 Datenschutz-Grundverordnung (DSGVO) z.H.: Datenschutzbeauftragter",[[null,null,"sedo","dsgvoseidank.de"]],[[null,null,"sedo","dsgvoseidank.de"]],[[null,null,"sedo","dsgvoseidank.de"]],[[null,null,"dataprotection","sedo.de"]],null,null,null,"<62b38643-8f21-562f-4809-3fff37507558@dsgvoseidank.de>"],["text","plain",["charset","UTF-8","format","flowed"],null,null,"8bit","1975","67",null,null,["en-US"],null],"89",null,null,null,null],"report",["report-type","delivery-status","boundary","57C845BC0006.1662379048\/isley.biz"],null,null,null]
```

**Comment by Orgoth** [comment]
patch for mailer-daemon status report

add after line 70 between signed and *
```php
            if (is_scalar($item) && strtolower($item) == 'report') {
                $subType = 'REPORT';
                $section = 'parameters';
                continue;
            }
```

processSubParts add query for processSubPartAsMessage
```php
        if( is_array($item[8]) ){
            $part->parts = [
                self::processSubPartAsMessage($item)
            ];
        }
```

processSubPartAsMessage add query for text after file_put_contents
```php
        if( strtolower($item[8][0]) === 'text' ){
            return self::textStructure($item[8]);
        }
```

function extractPartAsRfc822 add after "'ifdescription' => 0,"
```php
            'description'   => null,
```

function extractPartAsRfc822 add after "$dispositionParametersIndex = 11;"
```php
        if( is_scalar($item[4]) ){
            $part->ifdescription = 1;
            $part->description = $item[4];
        }
```

With these changes, the return structure is identical to old imap_fetchstructure.

**Comment by Orgoth** [comment]
patch alternative with multiple parts and alternative definition in row 3 instead of 2

extractPart add
```php
        if (is_scalar($item[3]) && strtolower($item[3]) == 'alternative') {
            return self::extractPartAsAlternative($item);
        }
```

JSON for verification:
```json
[[["text","plain",["charset","utf-8"],null,null,"quoted-printable","133","9",null,null,null,null],["text","html",["charset","utf-8"],null,null,"quoted-printable","222","9",null,null,null,null],["text","calendar",["method","REPLY","charset","utf-8"],null,null,"quoted-printable","3501","98",null,null,null,null],"alternative",["boundary","_=_swift_v4_1553521241_6fff07eef56d95546fbc6885392d333c_=_"],null,null,null],["text","plain",["name","MDNPart2.txt","charset","us-ascii"],null,null,"base64","346","5",null,["attachment",["filename","MDNPart2.txt"]],null,null],["text","plain",["name","MDNPart3.txt","charset","us-ascii"],null,null,"base64","4402","57",null,["attachment",["filename","MDNPart3.txt"]],null,null],"mixed",["boundary","_=_swift_v4_1553521240_8c41aa1cfbaf48ec9521f08edd62edc4_=_"],null,null,null]
```
With these changes, the return structure is identical to old imap_fetchstructure.

**Comment by Orgoth** [comment]
Patch signed message with alternative structure, but without encoding for the alternative.

@dicode-nl 
Would you please check this approach once?
I am not sure if I am just masking the problem or if it is actually correct.

The structure "alternative" does not have an encoding, instead an array with de-DE.
The old imap_fetchstructure returns 0 as encoding.
getEncoding is called with encodingIndex 5.
```php
    protected static function getEncoding($item, $encodingIndex)
    {
        if( isset($item[$encodingIndex]) && is_scalar(isset($item[$encodingIndex])) ) {
            return ( self::$encodingNumber[ strtoupper( $item[ $encodingIndex ] ) ] ?? 1 );
        }
        return 0;
    }
```

JSON for verification:
```json
[[["text","plain",["charset","utf-8"],null,null,"base64","3354","43",null,null,null,null],["text","html",["charset","utf-8"],null,null,"base64","14016","180",null,null,null,null],"alternative",["boundary","_000_DB9PR10MB44263917F030BCAD797C592380299DB9PR10MB4426EURP_"],null,["de-DE"],null],["application","x-pkcs7-signature",["name","smime.p7s"],null,null,"base64","5512",null,["attachment",["filename","smime.p7s"]],null,null],"signed",["protocol","application\/x-pkcs7-signature","micalg","sha-256","boundary","----1AD9E63099B861D3801E68D52A7487CE"],null,null,null]
```

**Comment by Orgoth** [comment]
I have more and more the feeling that the approach with the fixed index entries for the test is not necessarily target-leading.
These "mixed alternative" can theoretically always contain different sets of SubParts, so the position of the indication of which type it is keeps shifting.
In the current case, the e-mail "Apple-Mail" has five SubParts and the specification for Mixed is only in index 5 instead of in index 2 or 3 as before.

My first thought would be this.
array_search for mixed/alternative instead of the hardcoded index positions.
Similar to related.
```php
        if ( ($relatedIndex = array_search("related", $item)) !== false ) {
            return self::extractPartAsRelated($item, $relatedIndex);
        }
```

```json
[["text","plain",["charset","utf-8"],null,null,"quoted-printable","1373","59",null,null,null,null],[["text","html",["charset","utf-8"],null,null,"quoted-printable","768","11",null,null,null,null],["application","octet-stream",["x-unix-mode","0700","name","Pressemitteilung - Photovoltaikversicherung24 - BiPRO-BOX.pages"],null,null,"base64","1053984",null,["attachment",["filename","Pressemitteilung - Photovoltaikversicherung24 - BiPRO-BOX.pages"]],null,null],["text","html",["charset","us-ascii"],null,null,"7bit","208","0",null,null,null,null],["image","png",["x-unix-mode","0644","name","Bildschirmfoto 2021-10-27 um 18.52.40.png"],null,null,"base64","796760",null,["inline",["filename","Bildschirmfoto 2021-10-27 um 18.52.40.png"]],null,null],["text","html",["charset","utf-8"],null,null,"quoted-printable","24885","355",null,null,null,null],"mixed",["boundary","Apple-Mail=_1634CBE7-BC59-43FF-920E-47B48F8937D4"],null,null,null],"alternative",["boundary","Apple-Mail=_ECB27A4C-75E2-487F-894F-CAEBCB557FCC"],null,null,null]
```

**Comment by Orgoth** [comment]
```php
    protected static function extractPartAsMixed($item, $relatedIndex = 2)
    {
        $part = (object) [
            'type' => 1,
            'encoding' => self::getEncoding($item, $relatedIndex+2),
            'ifsubtype' => 1,
            'subtype' => 'MIXED',
            'ifdescription' => 0,
            'ifid' => 0,
            'ifdisposition' => 0,
            'disposition' => null,
            'ifdparameters' => 0,
            'dparameters' => null,
            'ifparameters' => 1,
            'parameters' => [],
            'parts' => []
        ];

        $offsetIndex = 0;
        foreach ($item as $subPart) {
            if (!is_array($subPart)) {
                break;
            }
            $offsetIndex++;
            $part->parts[] = self::extractPart($subPart);
        }

        $part->parameters = self::extractParameters($item[$offsetIndex+1], []);

        unset($part->disposition);
        unset($part->dparameters);

        return $part;
    }
```

```php
        if ( ($relatedIndex = array_search("mixed", $item)) !== false ) {
            return self::extractPartAsMixed($item, $relatedIndex);
        }
```php

**Comment by dicode-nl** [comment]
@Orgoth how about this version, it is more in line with the original c-client parsing which is used by php_imap

**Comment by Orgoth** [comment]
@dicode-nl 
This looks good, with the patches I provided I was able to pick up around 1000 mails from a wide variety of types.
I would now take the customization/simplification once and test again.

**Comment by Orgoth** [comment]
@dicode-nl 
Tested the new simplified version.
Works very good, I could receive every message without a single problem.

Thank you for the effort.

As a note, I still made changes to the Message.php and the ImapClient.php.

The background for this was as follows.
My email client only uses the uid's.
Therefore, there were problems here when retrieving the messages.
Because the Message.php uses the supplied ID to access the array.
Which in my case is the uid.

see: https://github.com/javanile/php-imap2/blob/main/src/Message.php#L145

Message.php on Line 133
The function fetchBody did not respect the parameter $flags and called fetch every time with $is_uid = false.

old
```php
        $messages = $client->fetch($imap->getMailboxName(), $messageNum, false, ['BODY['.$section.']']);
```
new
```php
        $isUid = boolval($flags & FT_UID);

        $messages = $client->fetch($imap->getMailboxName(), $messageNum, $isUid, ['BODY['.$section.']']);
```

ImapClient.php on Line 2484
Here, unfortunately, the is_uid was also ignored.
If now a call comes over a uid, then the reading of the array in the Message.php no longer works.
Message.php tries to access the array with the uid but ImapClient delivers the array with the server message id, not the uid.

The main reason is, the uid is delivered at the end ob the fetch string and the preg_match only gets the message-id.
I know about the function "msgno", but, this will do an additional request to the mail-server which is not needed.
We already have the uid for usage.

before on line 2484
```php
                $id = intval($m[1]);

                $result[$id]            = new MessageHeader;
                $result[$id]->id        = $id;
                $result[$id]->subject   = '';
                $result[$id]->messageID = 'mid:' . $id;
```
after
```php
            if (preg_match('/^\* ([0-9]+) FETCH/', $line, $m)) {
                $id = $msgid = intval($m[1]);
                if( $is_uid ){
                    $msgid = $message_set;
                }

                $result[$msgid]            = new MessageHeader;
                $result[$msgid]->id        = $id;
                $result[$msgid]->subject   = '';
                $result[$msgid]->messageID = 'mid:' . $id;
```

After that the array keys must be changed from $id to $msgid.
Afterwards the readout in Message.php works again and the object is returned instead of null.
If someone has a better solution or suggestion, I would be happy about suggestions.

**Comment by francescobianco** [comment]
Hi @dicode-nl ! I wanted to say hugely thank you for your work.
I have already integrated your work into the next release. I'm doing some testing but I'm sure it will be official.

Please consider supporting the users of this project by obviously charging a fee for your valuable work. Not to me but directly to those who ask for help.

Thanks too @Orgoth for the support of the project

**Pull request merged**
